### ISSUE TITLE
Regarding V2 scheme

### ISSUE THREAD

**Issue by S-Sarath10** [kellinwood/zip-signer#4]
Sir, can you add support for V2, V3, V4 signing schemes in the app. 
Zip-Signer is highly useful for signing .aab files. If you add V2 scheme it would be helpful for Siging apk as Google is changing its policy.

**Comment by omkar-tenkale** [comment]
Please add support for signature v2 as apps signed with zipsigner (v1) could not be installed on android 11 devices


> 
> APK Signature Scheme v2 now required :
> 
> "Apps that target Android 11 (API level 30) that are currently only signed using APK Signature Scheme v1 must now also be signed using APK Signature Scheme v2 or higher. Users can't install or update apps that are only signed with APK Signature Scheme v1 on devices that run Android 11."



https://developer.android.com/about/versions/11/behavior-changes-11#minimum-signature-scheme

**Comment by omkar-tenkale** [comment]
?
